Steps:
  - system: "Please only respond the boolean query generated. Do not put any redundant information in the response, the response will has to be executable in a search engine like PubMed directly."
    user: "For a systematic review titled {topic}, can you generate a systematic review Boolean query to find all included studies on PubMed for the review topic?"
    batch_size: 5
    example: false


